# Generated by Django 4.0.4 on 2022-05-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='feedback',
            new_name='message',
        ),
    ]
