# Generated by Django 4.0.5 on 2022-06-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_feedback_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
