# Generated by Django 4.0.6 on 2022-07-25 12:49

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contact_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='GymEnvironment',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='GymMusicSystem',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='HealthCalculator',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='MaintenanceofEquipements',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='NutritionistAdvisor',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='QualityofEquipements',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='QualityofPersonalTraining',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='TrainersBehavior',
            field=models.CharField(max_length=1, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='mid',
            field=models.CharField(max_length=10, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='feedback',
            name='remark',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=30, null=sqlalchemy.sql.expression.true),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=10, null=sqlalchemy.sql.expression.true),
        ),
    ]
